/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as RequestsRouteRouteImport } from './routes/requests/route'
import { Route as ModelsRouteRouteImport } from './routes/models/route'
import { Route as EmbeddingsRouteRouteImport } from './routes/embeddings/route'
import { Route as AppsRouteRouteImport } from './routes/apps/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as EmbeddingsIndexRouteImport } from './routes/embeddings/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as SettingsGrafanaRouteImport } from './routes/settings/grafana'
import { Route as SettingsAlertsRouteImport } from './routes/settings/alerts'
import { Route as ModelsRegistryRouteImport } from './routes/models/registry'
import { Route as ModelsProvidersRouteImport } from './routes/models/providers'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRouteRoute = RequestsRouteRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRouteRoute = ModelsRouteRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddingsRouteRoute = EmbeddingsRouteRouteImport.update({
  id: '/embeddings',
  path: '/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRouteRoute = AppsRouteRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestsRouteRoute,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelsRouteRoute,
} as any)
const EmbeddingsIndexRoute = EmbeddingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmbeddingsRouteRoute,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const SettingsGrafanaRoute = SettingsGrafanaRouteImport.update({
  id: '/grafana',
  path: '/grafana',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAlertsRoute = SettingsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ModelsRegistryRoute = ModelsRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => ModelsRouteRoute,
} as any)
const ModelsProvidersRoute = ModelsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ModelsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/apps': typeof AppsRouteRouteWithChildren
  '/embeddings': typeof EmbeddingsRouteRouteWithChildren
  '/models': typeof ModelsRouteRouteWithChildren
  '/requests': typeof RequestsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/models/providers': typeof ModelsProvidersRoute
  '/models/registry': typeof ModelsRegistryRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/grafana': typeof SettingsGrafanaRoute
  '/': typeof DashboardIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/embeddings/': typeof EmbeddingsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/models/providers': typeof ModelsProvidersRoute
  '/models/registry': typeof ModelsRegistryRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/grafana': typeof SettingsGrafanaRoute
  '/': typeof DashboardIndexRoute
  '/apps': typeof AppsIndexRoute
  '/embeddings': typeof EmbeddingsIndexRoute
  '/models': typeof ModelsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/apps': typeof AppsRouteRouteWithChildren
  '/embeddings': typeof EmbeddingsRouteRouteWithChildren
  '/models': typeof ModelsRouteRouteWithChildren
  '/requests': typeof RequestsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/models/providers': typeof ModelsProvidersRoute
  '/models/registry': typeof ModelsRegistryRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/grafana': typeof SettingsGrafanaRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/embeddings/': typeof EmbeddingsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/apps'
    | '/embeddings'
    | '/models'
    | '/requests'
    | '/settings'
    | '/models/providers'
    | '/models/registry'
    | '/settings/alerts'
    | '/settings/grafana'
    | '/'
    | '/apps/'
    | '/embeddings/'
    | '/models/'
    | '/requests/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/models/providers'
    | '/models/registry'
    | '/settings/alerts'
    | '/settings/grafana'
    | '/'
    | '/apps'
    | '/embeddings'
    | '/models'
    | '/requests'
    | '/settings'
  id:
    | '__root__'
    | '/_dashboard'
    | '/apps'
    | '/embeddings'
    | '/models'
    | '/requests'
    | '/settings'
    | '/models/providers'
    | '/models/registry'
    | '/settings/alerts'
    | '/settings/grafana'
    | '/_dashboard/'
    | '/apps/'
    | '/embeddings/'
    | '/models/'
    | '/requests/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AppsRouteRoute: typeof AppsRouteRouteWithChildren
  EmbeddingsRouteRoute: typeof EmbeddingsRouteRouteWithChildren
  ModelsRouteRoute: typeof ModelsRouteRouteWithChildren
  RequestsRouteRoute: typeof RequestsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embeddings': {
      id: '/embeddings'
      path: '/embeddings'
      fullPath: '/embeddings'
      preLoaderRoute: typeof EmbeddingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/requests/': {
      id: '/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof RequestsRouteRoute
    }
    '/models/': {
      id: '/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRouteRoute
    }
    '/embeddings/': {
      id: '/embeddings/'
      path: '/'
      fullPath: '/embeddings/'
      preLoaderRoute: typeof EmbeddingsIndexRouteImport
      parentRoute: typeof EmbeddingsRouteRoute
    }
    '/apps/': {
      id: '/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof AppsRouteRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/settings/grafana': {
      id: '/settings/grafana'
      path: '/grafana'
      fullPath: '/settings/grafana'
      preLoaderRoute: typeof SettingsGrafanaRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/alerts': {
      id: '/settings/alerts'
      path: '/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof SettingsAlertsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/models/registry': {
      id: '/models/registry'
      path: '/registry'
      fullPath: '/models/registry'
      preLoaderRoute: typeof ModelsRegistryRouteImport
      parentRoute: typeof ModelsRouteRoute
    }
    '/models/providers': {
      id: '/models/providers'
      path: '/providers'
      fullPath: '/models/providers'
      preLoaderRoute: typeof ModelsProvidersRouteImport
      parentRoute: typeof ModelsRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AppsRouteRouteChildren {
  AppsIndexRoute: typeof AppsIndexRoute
}

const AppsRouteRouteChildren: AppsRouteRouteChildren = {
  AppsIndexRoute: AppsIndexRoute,
}

const AppsRouteRouteWithChildren = AppsRouteRoute._addFileChildren(
  AppsRouteRouteChildren,
)

interface EmbeddingsRouteRouteChildren {
  EmbeddingsIndexRoute: typeof EmbeddingsIndexRoute
}

const EmbeddingsRouteRouteChildren: EmbeddingsRouteRouteChildren = {
  EmbeddingsIndexRoute: EmbeddingsIndexRoute,
}

const EmbeddingsRouteRouteWithChildren = EmbeddingsRouteRoute._addFileChildren(
  EmbeddingsRouteRouteChildren,
)

interface ModelsRouteRouteChildren {
  ModelsProvidersRoute: typeof ModelsProvidersRoute
  ModelsRegistryRoute: typeof ModelsRegistryRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteRouteChildren: ModelsRouteRouteChildren = {
  ModelsProvidersRoute: ModelsProvidersRoute,
  ModelsRegistryRoute: ModelsRegistryRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteRouteWithChildren = ModelsRouteRoute._addFileChildren(
  ModelsRouteRouteChildren,
)

interface RequestsRouteRouteChildren {
  RequestsIndexRoute: typeof RequestsIndexRoute
}

const RequestsRouteRouteChildren: RequestsRouteRouteChildren = {
  RequestsIndexRoute: RequestsIndexRoute,
}

const RequestsRouteRouteWithChildren = RequestsRouteRoute._addFileChildren(
  RequestsRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAlertsRoute: typeof SettingsAlertsRoute
  SettingsGrafanaRoute: typeof SettingsGrafanaRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAlertsRoute: SettingsAlertsRoute,
  SettingsGrafanaRoute: SettingsGrafanaRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AppsRouteRoute: AppsRouteRouteWithChildren,
  EmbeddingsRouteRoute: EmbeddingsRouteRouteWithChildren,
  ModelsRouteRoute: ModelsRouteRouteWithChildren,
  RequestsRouteRoute: RequestsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
