/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as RequestsRouteRouteImport } from './routes/requests/route'
import { Route as EmbeddingsRouteRouteImport } from './routes/embeddings/route'
import { Route as AppsRouteRouteImport } from './routes/apps/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as EmbeddingsIndexRouteImport } from './routes/embeddings/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRouteRoute = RequestsRouteRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddingsRouteRoute = EmbeddingsRouteRouteImport.update({
  id: '/embeddings',
  path: '/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRouteRoute = AppsRouteRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestsRouteRoute,
} as any)
const EmbeddingsIndexRoute = EmbeddingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmbeddingsRouteRoute,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/apps': typeof AppsRouteRouteWithChildren
  '/embeddings': typeof EmbeddingsRouteRouteWithChildren
  '/requests': typeof RequestsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/': typeof DashboardIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/embeddings/': typeof EmbeddingsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/': typeof DashboardIndexRoute
  '/apps': typeof AppsIndexRoute
  '/embeddings': typeof EmbeddingsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/apps': typeof AppsRouteRouteWithChildren
  '/embeddings': typeof EmbeddingsRouteRouteWithChildren
  '/requests': typeof RequestsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/embeddings/': typeof EmbeddingsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/apps'
    | '/embeddings'
    | '/requests'
    | '/settings'
    | '/settings/models'
    | '/settings/providers'
    | '/'
    | '/apps/'
    | '/embeddings/'
    | '/requests/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings/models'
    | '/settings/providers'
    | '/'
    | '/apps'
    | '/embeddings'
    | '/requests'
    | '/settings'
  id:
    | '__root__'
    | '/_dashboard'
    | '/apps'
    | '/embeddings'
    | '/requests'
    | '/settings'
    | '/settings/models'
    | '/settings/providers'
    | '/_dashboard/'
    | '/apps/'
    | '/embeddings/'
    | '/requests/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AppsRouteRoute: typeof AppsRouteRouteWithChildren
  EmbeddingsRouteRoute: typeof EmbeddingsRouteRouteWithChildren
  RequestsRouteRoute: typeof RequestsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embeddings': {
      id: '/embeddings'
      path: '/embeddings'
      fullPath: '/embeddings'
      preLoaderRoute: typeof EmbeddingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/requests/': {
      id: '/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof RequestsRouteRoute
    }
    '/embeddings/': {
      id: '/embeddings/'
      path: '/'
      fullPath: '/embeddings/'
      preLoaderRoute: typeof EmbeddingsIndexRouteImport
      parentRoute: typeof EmbeddingsRouteRoute
    }
    '/apps/': {
      id: '/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof AppsRouteRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AppsRouteRouteChildren {
  AppsIndexRoute: typeof AppsIndexRoute
}

const AppsRouteRouteChildren: AppsRouteRouteChildren = {
  AppsIndexRoute: AppsIndexRoute,
}

const AppsRouteRouteWithChildren = AppsRouteRoute._addFileChildren(
  AppsRouteRouteChildren,
)

interface EmbeddingsRouteRouteChildren {
  EmbeddingsIndexRoute: typeof EmbeddingsIndexRoute
}

const EmbeddingsRouteRouteChildren: EmbeddingsRouteRouteChildren = {
  EmbeddingsIndexRoute: EmbeddingsIndexRoute,
}

const EmbeddingsRouteRouteWithChildren = EmbeddingsRouteRoute._addFileChildren(
  EmbeddingsRouteRouteChildren,
)

interface RequestsRouteRouteChildren {
  RequestsIndexRoute: typeof RequestsIndexRoute
}

const RequestsRouteRouteChildren: RequestsRouteRouteChildren = {
  RequestsIndexRoute: RequestsIndexRoute,
}

const RequestsRouteRouteWithChildren = RequestsRouteRoute._addFileChildren(
  RequestsRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AppsRouteRoute: AppsRouteRouteWithChildren,
  EmbeddingsRouteRoute: EmbeddingsRouteRouteWithChildren,
  RequestsRouteRoute: RequestsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
